### ISSUE TITLE
Empty window after 'npm start'

### ISSUE THREAD

**Issue by desfero** [ppoffice/Hozz#10]
@ppoffice, I try to build your app from master branch, but i have only empty window 
![app](https://cloud.githubusercontent.com/assets/7031578/13715652/864bdb2a-e7d6-11e5-997e-f57dda3b6f4b.png)

I have following commands flow:

```
git clone https://github.com/ppoffice/Hozz.git
cd Hozz
npm install
gulp
npm start 
```

Did you have similar bug?

**Comment by ppoffice** [comment]
Which OS are you using?

**Comment by desfero** [comment]
Windows 10. :)  I also tried to run other electron application and all work correct

**Comment by ppoffice** [comment]
I think you can try to remove node_modules and reinstall all the dependencies, then try to build the app from start.

**Comment by desfero** [comment]
it doesn't help, also i have the same issue on my windows 8

**Comment by ppoffice** [comment]
Uncomment this line and rebuild the app to see what's going on when Hozz starts:
https://github.com/ppoffice/Hozz/blob/master/src/browser.js#L123

Then put a screenshot here. Thank you.

**Comment by desfero** [comment]
I found a bug in language.js file. You don't check if we have translations for selected language. Also i change `navigator.language` to `navigator.languages` for better language inference.

Pull request with changes #11 

Thank you for your help.
