### ISSUE TITLE
Getting trouble with updating to 0.1.3

### ISSUE THREAD

**Issue by hengyuanma** [ppoffice/Hozz#16]
OS: Windows 10 x64
Hozz Current Version: 0.1.0
It keeps reminding me to update to the newest 0.1.3, but I just can't download the package via Hozz itself.
Plz upload the latest to BaiduYun or the homepage?

**Comment by ppoffice** [comment]
You can manually download: https://github.com/ppoffice/Hozz/releases/download/v0.1.3/core.zip and unzip it to `(your Hozz install dir)/resources/app` to overwrite all the files.

**Comment by mykiwi** [comment]
I just update the app, and I got this message:

<img width="383" alt="capture d ecran 2016-05-15 a 12 28 50" src="https://cloud.githubusercontent.com/assets/334432/15273392/bda0e03a-1a98-11e6-995c-c185116fb670.png">

**Comment by ppoffice** [comment]
@romqin There may be some file permission issues if you directly put the update files under the App resource folder. Also you should check if you unzip the archive to the right place.
