### ISSUE TITLE
最新版在Win10上的问题？

### ISSUE THREAD

**Issue by ghost** [ppoffice/Hozz#18]
近来0.1.3版在32位Win10上启动时弹出窗口异常缓慢，点击程序设置窗口也是如此，且原有的状态栏图标变成了空白，不知何故？

**Comment by ppoffice** [comment]
请尝试下载windows7的那个压缩包，那个是未精简的程序

**Comment by ghost** [comment]
谢谢！按您的指引问题已解决。
