### ISSUE TITLE
The main program isn't executable on Linux by default

### ISSUE THREAD

**Issue by K-Guan** [ppoffice/Hozz#2]
I have to use `chmod` to set it as executable after I download the package [from here](http://blog.zhangruipeng.me/Hozz/) (Linux x64 version) and extracted the `.tar.gz` package:

```
kevin@Arch ~/D/Hozz-linux-x64> ls
content_shell.pak  Hozz  icudtl.dat  libgcrypt.so.11  libnode.so  locales/  natives_blob.bin  resources/
kevin@Arch ~/D/Hozz-linux-x64> chmod 755 Hozz
```

**Comment by ppoffice** [comment]
Thanks for pointing it out.

I tested it on Ubuntu and it seems that the default permission of `./Hozz` in the archive is already `0755`. Maybe I should add a notice in the README.

**Comment by K-Guan** [comment]
Ahhh, my bad. Shouldn't use `7z X [...].tar.gz` instead of `tar xzf [...].tar.gz`.
