### ISSUE TITLE
I can not run it in Win 10 education 14393 edition.

### ISSUE THREAD

**Issue by CosmosGlow** [ppoffice/Hozz#22]
My pc has not  run Hozz before , and I used Hozz first  time , but I can not run it .  after double clicked Hozz.exe , there is nothing show out.

**Comment by CosmosGlow** [comment]
@ppoffice , thank you very much .

**Comment by ppoffice** [comment]
@HUbaoguo 
Please try these uncompressed versions:
https://github.com/ppoffice/Hozz/releases/tag/v0.1.0

**Comment by CosmosGlow** [comment]
thank you ,it is ok now.
