### ISSUE TITLE
怎么样不让Hozz更新host文件？

### ISSUE THREAD

**Issue by digicolor** [ppoffice/Hozz#23]
每次打开Hozz，都会用Hozz老的host配置自动替换掉电脑已有的host，但是电脑里面的host确实最新的，怎样让hozz打开，用电脑的host替换hozz内的host配置？

**Comment by ppoffice** [comment]
@digicolor Hozz需要保证系统hosts和软件里面的一致才能保证软件的行为正常，无法判断用户是否通过其他方式更改了hosts。请尽量使用Hozz编辑hosts而避免手动编辑。
