### ISSUE TITLE
[Server2008R2]无法打开

### ISSUE THREAD

**Issue by rmnof** [ppoffice/Hozz#24]
![1](https://cloud.githubusercontent.com/assets/18734333/20378360/8b4afa88-acd0-11e6-9dcf-e4a0c2f0ac4e.png)

问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	Hozz.exe
  应用程序版本:	0.36.2.0
  应用程序时间戳:	567cd902
  故障模块名称:	Hozz.exe
  故障模块版本:	0.36.2.0
  故障模块时间戳:	567cd902
  异常代码:	80000003
  异常偏移:	00000000002c2ca9
  OS 版本:	6.1.7601.2.1.0.274.10
  区域设置 ID:	2052
  其他信息 1:	bd98
  其他信息 2:	bd983ac51b814a0a627d08d906c743dc
  其他信息 3:	337a
  其他信息 4:	337ad6eee35f9e4fb4942c3412c0b10a

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\windows\system32\zh-CN\erofflps.txt

请问这个问题可以解决吗？

**Comment by ppoffice** [comment]
@ioperat 
请尝试未压缩版本
https://github.com/ppoffice/Hozz/releases/tag/v0.1.0
