### ISSUE TITLE
hozz用不了啊

### ISSUE THREAD

**Issue by FUyying** [ppoffice/Hozz#29]
为什么我什么都设置好了还是不能上外网呢？远程hosts地址填了https://raw.githubusercontent.com/racaljk/hosts/master/hosts   
除了这个::1	localhost ip6-localhost ip6-loopback其它都是绿的，所以是为什么还不能上呢。。 @ppoffice

**Comment by ppoffice** [comment]
@FUyying 
你点击侧边栏的Hosts项目最左侧的开关了么？

**Comment by FUyying** [comment]
就是新建的hosts项目吗？都点了，左边两个都绿了

**Comment by ppoffice** [comment]
@FUyying 
请检查系统的hosts文件是否发生改变

**Comment by FUyying** [comment]
怎么检查有没有改变。。

**Comment by ppoffice** [comment]
@FUyying 
检查下`C:\Windows\System32\drivers\etc\hosts`的内容是否和你预想的一致，如果内容对的话，强制清空下DNS缓存：打开CMD并输入`ipconfig /flushdns`；否则就要看下Hozz是否有权限更改系统的hosts文件了。

**Comment by FUyying** [comment]
hosts文件和那个地址的内容一样，现在清空DNS缓存了，打开网页说 
未连接到互联网
代理服务器出现问题，或者地址有误。
可是国内的网就能上

**Comment by ppoffice** [comment]
你访问的网址可能需要连接到https开头的网址，比如http://www.google.com就要访问https://www.google.com

**Comment by FUyying** [comment]
还是不行。。
其实我在官网上下载的hozz无法打开，然后别人给我0.1.0版本后，再更新好的，也不知是不是这个原因

**Comment by ppoffice** [comment]
请在CMD输入如下命令：
```bat

nslookup www.google.com
nslookup www.google.com 8.8.8.8
```
并贴下结果。

**Comment by FUyying** [comment]
nslookup www.goole.com
服务器：ns1halyptt.net.cn
Address:202.102.227.68

非权威应答：
名称：www.goole.com
Address:87.106.83.127

nslookup www.google.com 8.8.8.8
服务器：goole-public-dns-a.goole.com
Adress:8.8.8.8

非权威应答：
名称：www.goole.com
Adress:87.106.83.127

**Comment by ppoffice** [comment]
@FUyying 
可能是DNS被污染了，请尝试更换DNS服务器。

**Comment by 0f7b90** [comment]
为什么设置按钮按了没反应啊.....任务栏里出现一个settings框，但没有弹窗，求解....

**Comment by ppoffice** [comment]
@yangzheng1994 请具体描述下运行环境和出现问题的状况
