### ISSUE TITLE
MacOS:10.12.2     无法获取权限

### ISSUE THREAD

**Issue by Here21** [ppoffice/Hozz#30]

**Comment by ppoffice** [comment]
@Here21 
请具体描述下软件运行的环境，用户账户等等条件

**Comment by Here21** [comment]
>Mac book pro 2016 
15‘ touch-bar
macOS Sierra 10.12.2
用户账户：管理员

问题描述：打开软件，自动更新到最新版，之后新建并添加了hosts，然后提示输入密码，完成之后hozz下方红色条提示无法获取权限，重复多次都是这样

之前在旧电脑上用过，Ubuntu，win10，Mac mini都正常使用

**Comment by ppoffice** [comment]
@Here21 
在问题解决之前，请先在terminal中手动调整下hosts的文件权限：
```bash
sudo chown your_username /etc/hosts
sudo chmod 644 /etc/hosts
```
这个问题可能和macOS有关系，我会进一步研究下。

**Comment by ppoffice** [comment]
@Here21 这与新系统的sudo更改有关：https://github.com/automation-stack/electron-sudo/issues/39
我建议的做法是手动添加当前用户的hosts写权限：
```
sudo chmod +a "`whoami` allow read,write" /etc/hosts
```
这个Bug需要等`electron-sudo`解决新系统的问题。
