### ISSUE TITLE
能否编译最新windows平台的Hozz?

### ISSUE THREAD

**Issue by xmbhsqktdqfpqdy** [ppoffice/Hozz#35]
以前的老版本今天提示有新版本，但是一直无法自动更新成功。而这又只有源码。

**Comment by ppoffice** [comment]
@z344257899 
我是打算大版本更新的时候升级运行时的，不过如果只是提示无法更新成功的话说明应该不是运行时的问题。请尝试手动下载Releases中的最新版本的core.zip并解压覆盖到程序的`resources/app`目录。

**Comment by xmbhsqktdqfpqdy** [comment]
3q
