### ISSUE TITLE
官网下载的不是最新？

### ISSUE THREAD

**Issue by jp1017** [ppoffice/Hozz#36]
http://blog.zhangruipeng.me/Hozz/

这里下载的 linux 版本 x64是0.0.1版本而不是最新的0.1.4？

怎么回事？

**Comment by ppoffice** [comment]
@jp1017
软件会有更新提示

**Comment by jp1017** [comment]
@ppoffice 点了，downing update 然后applying , 之后就一直applying, 后面没有了，win10正常升级，我的是ubuntu16.04, 上一个版本0.0.1和0.1.3一样效果。。

**Comment by ppoffice** [comment]
@jp1017 是不是你在Ubuntu下把软件放到了一个它自己没有写权限的目录中？

**Comment by jp1017** [comment]
在 下载文件夹下, 可以写入的

**Comment by ppoffice** [comment]
@jp1017 我上传了新版本到百度网盘上了，请尝试覆盖更新一下

**Comment by jp1017** [comment]
可以了，谢谢！
