### ISSUE TITLE
Repeated Grant permission on Windows 10 x64

### ISSUE THREAD

**Issue by sguergachi** [ppoffice/Hozz#39]
Every time I select the "All" rule set I get asked to "Grant Permission". I keep granting permission but it doesn't seem to stop asking. I always launch the app with Admin privileges.

**Comment by sguergachi** [comment]
I noticed that my host file was never edited even after repeatedly giving permission.

**Comment by ppoffice** [comment]
@sguergachi Could you please post last few lines of the log file (`%USERPROFILE%/.Hozz/log.txt`) here? Thank you.

**Comment by sguergachi** [comment]
I managed to fix it by deleting the .Hozz folder and restarting. Don't know why but it's fixed
