### ISSUE TITLE
0.1.4无法自动更新远程host地址

### ISSUE THREAD

**Issue by 0f7b90** [ppoffice/Hozz#41]
每次都要删掉再添加一次才更新，上一个版本似乎没有这个问题

**Comment by ppoffice** [comment]
@yangzheng1994 
请备份用户目录下的`.Hozz`文件夹后删除这个文件夹，再重新添加hosts。
另外请贴一下此文件夹下的log.txt中最近几次记录。

**Comment by 0f7b90** [comment]
恢复正常了，谢谢（没找到log.txt）
