### ISSUE TITLE
v0.1.4：无法授予权限

### ISSUE THREAD

**Issue by haozhu18** [ppoffice/Hozz#43]
win10 x64家庭版
始终显示没有写入系统hosts的权限，点击授予权限没有反应
以下为日志：
[2017-5-28 16:11:37.910]
Error: ENOENT: no such file or directory, open 'C:\Users\����\AppData\Local\Temp\batch-0.18028832785785198.bat'
    at Error (native)
[2017-5-28 16:12:32.639]
Error: ENOENT: no such file or directory, open 'C:\Users\����\AppData\Local\Temp\batch-0.2084602036047727.bat'
    at Error (native)
[2017-5-28 16:12:44.1]
Error: ENOENT: no such file or directory, open 'C:\Users\����\AppData\Local\Temp\batch-0.5196671718731523.bat'
    at Error (native)
[2017-5-28 16:13:4.144]
Error: ENOENT: no such file or directory, open 'C:\Users\����\AppData\Local\Temp\batch-0.663841022644192.bat'
    at Error (native)

**Comment by Mooooooon** [comment]
看上去是因为中文路径

**Comment by haozhu18** [comment]
上次升级成专业版就好了，不记得是不是因为中文路径了，不过还是谢谢啦
