### ISSUE TITLE
你好，请问图标是用什么工具做的啊？想加个功能，需要新增个图标，请问有空给个支持不？

### ISSUE THREAD

**Issue by kerwin612** [ppoffice/Hozz#46]
你好，请问图标是用什么工具做的啊？想加个功能，需要新增个图标，请问有空给个支持不？

**Comment by ppoffice** [comment]
@ileler http://www.iconfont.cn/

**Comment by kerwin612** [comment]
@ppoffice 那能不能把我加入这个iconfont项目的成员中去呢？我单独生成的加入到svg不生效。我的iconfont用户名也是“ileler”

**Comment by ppoffice** [comment]
@ileler 我已经很久没登陆过这个项目了，所以现在不记得用户名密码了

**Comment by kerwin612** [comment]
@ppoffice 那就不好办了吧？那现有的svg没法导入为项目，想新增svg图标就没法直接复用你之前那套图标逻辑了。能否尝试找回看看？

**Comment by kerwin612** [comment]
....
