### ISSUE TITLE
Doesn't open in Win 7 Home Premium

### ISSUE THREAD

**Issue by Braunson** [ppoffice/Hozz#5]
Nothing happens when executing the Hozz.exe on Windows 7 Home Premium (x64). There's not even an error log or error message.

**Comment by ppoffice** [comment]
After testing on Virtualbox, I think it is the upx compression caused this problem.
You can try the uncompressed versions. And if it works, please let me know :smiley: 

https://github.com/ppoffice/Hozz/releases/tag/v0.1.0

**Comment by Braunson** [comment]
@ppoffice Yep uncompressed version works for me. :+1:
