### ISSUE TITLE
讲道理，这个 Node.js 写的程序啊

### ISSUE THREAD

**Issue by Garfield550** [ppoffice/Hozz#7]
卡的帧数都不如扫雷。
任务管理器里内存占用 41M，说得过去，可是 CPU 占用一直 0% 并且无法点选任何东西是怎么回事？

后来我发现这个程序怎么用了，就是先激活窗口，点选你想看的 Hosts 标签，然后让这个程序失去焦点，再激活窗口就行了。

**Comment by ppoffice** [comment]
什么系统下使用的呢？

**Comment by Garfield550** [comment]
OS 名称:          Microsoft Windows Embedded 8.1 Industry Pro
OS 版本:          6.3.9600 暂缺 Build 9600
OS 制造商:        Microsoft Corporation

**Comment by ppoffice** [comment]
嵌入式么？请尝试 https://github.com/ppoffice/Hozz/releases/tag/v0.1.0 下的无压缩版本，如果问题依旧的话应该就是应该是Electron的适配问题。

**Comment by Garfield550** [comment]
主机名:           坐和放宽
OS 名称:          Microsoft Windows Embedded 8.1 Industry Pro
OS 版本:          6.3.9600 暂缺 Build 9600
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构件类型:      Multiprocessor Free
初始安装日期:     2015/4/15, 22:49:39
系统启动时间:     2016/1/20, 13:55:50
系统制造商:       LENOVO
系统型号:         IdeaPad U410
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: Intel64 Family 6 Model 58 Stepping 9 GenuineIntel ~1701 Mhz

**Comment by ppoffice** [comment]
我刚刚在VirtualBox的Microsoft Windows Embedded 8.1 Industry Pro下面测试了一下，压缩和无压缩的版本都没有什么问题。这个Bug复现确实有些麻烦。如果你在使用无压缩版本之后仍然卡帧严重，可以检查下DirectX有没有正确开启。

**Comment by Garfield550** [comment]
感谢您的解答，不过最近由于需要开发 UWP 应用的原因切换到了 Windows 10，并且 Hozz 已经升级到了 0.1.1，可能不需要对这个问题进行过多的研究了，如果您认为可以关闭这个 Issues，那么请您关闭。
