### ISSUE TITLE
Ghost window on OS X after typing admin password

### ISSUE THREAD

**Issue by daniele-orlando** [ppoffice/Hozz#8]
OSX El Capitan

The app started, asked for admin password, restarted and now doesn't appear anymore.

**Comment by ppoffice** [comment]
Does the app shows a tray icon?

**Comment by daniele-orlando** [comment]
No. And the app doesn't quit too. I have to terminate/kill it from the Activity Manager.

**Comment by ppoffice** [comment]
What is the version of the app? Also, you can find log file under ~/.Hozz/ and post it here.

**Comment by daniele-orlando** [comment]
Hozz Version: `0.36.2`

```
ls -1 ~/.Hozz/

7pdwqsmdrf9ouksv
manifest.json
```

```
cat ~/.Hozz/7pdwqsmdrf9ouksv

##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1   localhost
255.255.255.255 broadcasthost
::1             localhost 
```

```
cat ~/.Hozz/manifest.json

{"hosts":[{"uid":"7pdwqsmdrf9ouksv","url":"","name":"Default Hosts","index":0,"online":true,"count":3}],"online":true,"language":"it"}
```

I tried deleting the `~/.Hozz/` directory, but every time it is recreated with the same ghost window result.

**Comment by daniele-orlando** [comment]
I don't know if there is a connection, but the user I use on my OS X system is a regular user, not an administrator user. This means that has no access to sudo/su capabilities.

I used another tool for the same purpose of Hozz, which was called Horst, that installed a privileged helper inside the `/Library/PrivilegedHelperTools/`.

There is no such helper for Hozz. I'm wondering how it can edit the root.wheel protected `/etc/hosts` file.

---

**Update 1:**
Reading the Hozz source code I discovered how Hozz writes the `/etc/hosts` file. So it seams to be a problem connected to the `sudo chmod` you are using to make the `/etc/hosts` file writable.

---

**Update 2:**
Changing the `/etc/hosts` permissions to `666` doesn't fix the problem.

**Comment by ppoffice** [comment]
Thanks for reporting this. I will take a look soon.

**Comment by daniele-orlando** [comment]
I'm posting some resources that could be useful to **correctly** implement a privileged helper.

https://developer.apple.com/library/mac/documentation/Security/Conceptual/SecureCodingGuide/Articles/AccessControl.html
https://developer.apple.com/library/mac/documentation/Security/Conceptual/authorization_concepts/01introduction/introduction.html
https://developer.apple.com/library/mac/samplecode/EvenBetterAuthorizationSample/Introduction/Intro.html

**Comment by ppoffice** [comment]
I tested it on OS X with a normal account and found no ghost window. But this will not fix the privilege issue. I think I may come up with a solution afterwards.

**Comment by ppoffice** [comment]
#9
