### ISSUE TITLE
Permission issue on OS X 10.11.3

### ISSUE THREAD

**Issue by divyenduz** [ppoffice/Hozz#9]
Hi,

<img width="1280" alt="screen shot 2016-03-05 at 9 44 59 pm" src="https://cloud.githubusercontent.com/assets/746482/13548664/8b3ff130-e31b-11e5-8cbe-28eb4026b2b0.png">

The message that "You don't have permission to write to hosts file", won't go away. When I click on "Grant Permission" button, sometimes nothing happens (message goes away), sometimes I am asked for my password and then the message goes away.

But when I click anywhere, this message pops up.

I have not built from the code, I am using the stable version from website with version number 0.1.2

I have not looked into code at all but I am comfortable, so, let me know if you need any inputs from my end. Will try the latest build from master on my machine tonight. 

Love the idea of this app.

**Comment by divyenduz** [comment]
I am able to replicate the same issue in master also. After building the project from github code. 
Not sure about the reason though, yet.

**Comment by ppoffice** [comment]
Did you use a normal system account without writing permission to system files?

**Comment by divyenduz** [comment]
I use an administrator account. I can manually edit hosts file using sudo

**Comment by ppoffice** [comment]
User's ownership of this file does not change after clicking on "Grant Permission" button. I will fix this in a day or two. Thank you for issuing this.

**Comment by divyenduz** [comment]
Thanks! Please put the related commit and close this ticket. I will then
build the latest app from here!

On Sun, Mar 6, 2016 at 1:04 PM, Ruipeng Zhang notifications@github.com
wrote:

> User's ownership of this file does not change after clicking on "Grant
> Permission" button. I will fix this in a day or two. Thank you for issuing
> this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ppoffice/Hozz/issues/9#issuecomment-192820903.

## 

Divyendu Singh
+91-984-522-5282
Web: www.divyendusingh.com

**Comment by divyenduz** [comment]
I think this is resolved in 0.1.3  
Thanks, working like a charm.
